[stage_01.boot_inputs]
os_name = "IuppiterOS"
overlay_kind = "openrc"
required_services = ["networking", "dhcpcd", "sshd"]
openrc_inittab = "serial_only"
profile_overlay = "distro-variants/iuppiter/profile/live-overlay"

[stage_01.boot_inputs.rootfs_source]
kind = "recipe_custom"
recipe_script = "distro-builder/recipes/alpine-stage01-rootfs.rhai"

[stage_01.boot_inputs.rootfs_source.defines]
ALPINE_RELEASE_BRANCH = "v3.23"
ALPINE_EXTENDED_VERSION = "3.23.2"
ALPINE_EXTENDED_SHA256 = "8d50854936dba58e7616ac3bfa07ad67dac0347305fec1cba6d288cf5df1577d"
ALPINE_APK_TOOLS_VERSION = "3.0.5-r0"
ALPINE_APK_TOOLS_SHA256 = "6e832468b4efebd6ab7245e4989ca38b6e4589a9772d52a03b58c690a7aeacbe"
ALPINE_STAGE01_PROFILE = "iuppiter"
